--- 
abstract: validate assembly stash with Rx (from JSON in kit)
author: 
  - Ricardo SIGNES <rjbs@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.004
license: perl
name: Email-MIME-Kit-Validator-Rx
requires: 
  Data::Rx: 0.007
  Data::Rx::TypeBundle::Perl: 0
  Email::MIME::Kit: 2
  JSON: 2
version: 0.003
